spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/masil
    username: root
    password:

  jpa:
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: [IAM 계정의 accessKey]
      secret-key: [IAM 계정의 secretKey]
    region:
      static: [버킷의 리전]
    s3:
      bucket: [버킷 이름]
    stack:
      auto: false

cdn:
  domain : [cloudfront domain]

logging:
  level:
    org:
      hibernate:
        type:
          nodeValue: trace
          descriptor:
            sql: DEBUG
        SQL: DEBUG

jwt:
  header: Authorization
  secret: [secretKey]
  access-token-expire-time: 86400000
  refresh-token-expire-time: 86400000